# -*- coding: utf-8 -*-
"""Poc_segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mYTIye9F2eexCnVgQAffcQtL4XyeOVmj
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans


# Load your trained model
kmeans = pickle.load(open('kmeans.pkl', 'rb'))

st.title('Customer Segmentation Tool')

# File uploader
uploaded_file = st.file_uploader("Choose an Excel file", type=['csv'])
if uploaded_file is not None:
    data = pd.read_csv(uploaded_file,sep='\t',parse_dates=['Dt_Customer'])
    scaler = StandardScaler()
    scaled_data = scaler.fit_transform(data)
    predictions = kmeans.fit_predict(scaled_data)  # adjust the column name
    data['Cluster'] = predictions
    st.write(df_test)







